// routes/home.js
const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
    // Sample user object
    const intro = {
        statement: 'Let\'s explore Pet section',
        name: 'Yash joshi',
Cat: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia quo sit deserunt velit ea dolore, quibusdam aut quod fuga. Eos repellat reiciendis delectus dolorum, tenetur distinctio id eveniet atque quas. Quod, dolor illum consequatur laborum ea a voluptate placeat obcaecati? Quos saepe temporibus culpa ducimus pariatur ab quo optio, nihil iste porro sint totam quod ad iure inventore tenetur debitis, ipsam vel? Non laborum sequi, libero, possimus consectetur perspiciatis id recusandae veritatis incidunt exercitationem aliquam, hic eius dolorem totam natus autem beatae doloribus! Exercitationem quia quam nam ullam ex iusto, doloremque numquam illo delectus tempore vitae error tenetur dolorem laborum facere officiis perspiciatis assumenda dicta nihil saepe libero aliquam! Nihil fugiat, iusto rem quae nisi at a eligendi quisquam, dolore amet accusantium eveniet minima sint modi omnis fugit, non illo consequuntur magni nesciunt reprehenderit aliquam. Tenetur dolorem nulla vel, impedit omnis, reprehenderit quos dicta eligendi aliquid ad, unde quas labore' ,       
Cow: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia quo sit deserunt velit ea dolore, quibusdam aut quod fuga. Eos repellat reiciendis delectus dolorum, tenetur distinctio id eveniet atque quas. Quod, dolor illum consequatur laborum ea a voluptate placeat obcaecati? Quos saepe temporibus culpa ducimus pariatur ab quo optio, nihil iste porro sint totam quod ad iure inventore tenetur debitis, ipsam vel? Non laborum sequi, libero, possimus consectetur perspiciatis id recusandae veritatis incidunt exercitationem aliquam, hic eius dolorem totam natus autem beatae doloribus! Exercitationem quia quam nam ullam ex iusto, doloremque numquam illo delectus tempore vitae error tenetur dolorem laborum facere officiis perspiciatis assumenda dicta nihil saepe libero aliquam! Nihil fugiat, iusto rem quae nisi at a eligendi quisquam, dolore amet accusantium eveniet minima sint modi omnis fugit, non illo consequuntur magni nesciunt reprehenderit aliquam. Tenetur dolorem nulla vel, impedit omnis, reprehenderit quos dicta eligendi aliquid ad, unde quas labore',
        dog: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia quo sit deserunt velit ea dolore, quibusdam aut quod fuga. Eos repellat reiciendis delectus dolorum, tenetur distinctio id eveniet atque quas. Quod, dolor illum consequatur laborum ea a voluptate placeat obcaecati? Quos saepe temporibus culpa ducimus pariatur ab quo optio, nihil iste porro sint totam quod ad iure inventore tenetur debitis, ipsam vel? Non laborum sequi, libero, possimus consectetur perspiciatis id recusandae veritatis incidunt exercitationem aliquam, hic eius dolorem totam natus autem beatae doloribus! Exercitationem quia quam nam ullam ex iusto, doloremque numquam illo delectus tempore vitae error tenetur dolorem laborum facere officiis perspiciatis assumenda dicta nihil saepe libero aliquam! Nihil fugiat, iusto rem quae nisi at a eligendi quisquam, dolore amet accusantium eveniet minima sint modi omnis fugit, non illo consequuntur magni nesciunt reprehenderit aliquam. Tenetur dolorem nulla vel, impedit omnis, reprehenderit quos dicta eligendi aliquid ad, unde quas labore!',
        Rabbit: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia quo sit deserunt velit ea dolore, quibusdam aut quod fuga. Eos repellat reiciendis delectus dolorum, tenetur distinctio id eveniet atque quas. Quod, dolor illum consequatur laborum ea a voluptate placeat obcaecati? Quos saepe temporibus culpa ducimus pariatur ab quo optio, nihil iste porro sint totam quod ad iure inventore tenetur debitis, ipsam vel? Non laborum sequi, libero, possimus consectetur perspiciatis id recusandae veritatis incidunt exercitationem aliquam, hic eius dolorem totam natus autem beatae doloribus! Exercitationem quia quam nam ullam ex iusto, doloremque numquam illo delectus tempore vitae error tenetur dolorem laborum facere officiis perspiciatis assumenda dicta nihil saepe libero aliquam! Nihil fugiat, iusto rem quae nisi at a eligendi quisquam, dolore amet accusantium eveniet minima sint modi omnis fugit, non illo consequuntur magni nesciunt reprehenderit aliquam. Tenetur dolorem nulla vel, impedit omnis, reprehenderit quos dicta eligendi aliquid ad, unde quas labore!',

    };

    // Render the 'index' view and pass the 'user' object to it
    res.render('index', { intro: intro });
});

module.exports = router;